[[constraint]]
  name = "github.com/Shopify/sarama"
  version = "1.13.0"

[[constraint]]
  branch = "master"
  name = "github.com/lib/pq"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"
